// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState,useEffect} from "react";
import { useNavigate } from 'react-router-dom';
import Steps from './Steps';

//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

const config = {
                    server : "localhost:5000"
                }



function Marketplace_(props,ref) {

    const navigate = useNavigate()

    const [allNFTData, setallNFTData] = useState({
        
    })

    let count = 0;

    const token = props.token;
    const settoken = props.settoken;
    
    const buyNFT = (token) => {

        settoken(prevState => {
            return {
                ...prevState,
                token : token
            }
        });

        let expiryTime = new Date(token.expiryTime*1000);

        token.expiryTimeISO = expiryTime.toLocaleDateString();

        let listingTime = new Date(token.listingTime*1000);

        token.listingTimeISO = listingTime.toLocaleDateString();

        
        navigate('/buyNftForm')
        
    };  
    
     
    useEffect(() => {

    let app = this;
    var url = 'http://'+config.server+'/getallmarketNFTs';
       
    console.log("url",url);	
    
    if (count == 0 )
    {
        count  = 1;
  
        fetch(url, {

    method: 'POST',
    mode: 'cors',

    headers: {
        'Accept': 'application/json',
        'Content-Type':'application/json',
          },	
                
            }).then(function(response,error) {
    

                if(response)
            {
                
                return response.json();
            }
        else 
            {
                console.log(error);
            }
            }).then(function(data){

                console.log("data",data);

                setallNFTData(prevState => {

                    return {
                        nfts: data.NFTs.reverse()
                          }
                    })
    
        })
    }   

},[count])   
    

        	
return(
            <div>           
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>
                            
                            <div className="columns">  
                            <div className="column">
                            <div className="has-text-centered">
                            <h3 className="title is-2 is-family-sans-serif"> Marketplace</h3>
                            <button className="button is-black"  onClick={() => navigate('/wallet')}>List my NFTs for sale</button>
                            </div>
                            </div>
                            </div>
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>

                            <div className="columns">  
                            <div className="column">
                            <Steps bar={"market"}/>

                            </div>
                            </div>
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>
                            <div className="columns is-centered">                               
                            <div className="column has-text-centered">
                            <p className="subtitle is-5 is-family-secondary">The Marketplace lists all NFTs on sale, including yours </p>
                            <p className="subtitle is-5 is-family-secondary">Here we'll switch to a buyer's role and buy a NFT. Click on Buy NFT on any card </p> 
                            
                            
                            </div>
                            </div>
                            

                            


                            <div className="columns is-multiline">    
                            
                                   
                            <div className = "column is-8 is-offset-2">
                             
                            <nav className="panel">
                            
                            <form className="box">
                            
                            {
                            allNFTData.nfts?


                            
                            <div className="columns is-multiline">
                               
                            {    
                            
                            allNFTData.nfts.map((nft,index) => {

                                let urlIPFS = 'http://127.0.0.1:8080/ipfs/'+nft.ipfsHash; 

                                let expiryTime = nft.expiryTime
                                let currentTime = Math.floor((Date.now()) / 1000);

                                console.log(currentTime,"currentTime");

                                let timeLeft;


                                //let expiredTime = new Date(nft.expiryTime*1000);
                                //let listingTime = new Date(nft.listingTime*1000);


                                if (currentTime > expiryTime)
                                 timeLeft = "Expired";
                                else
                                {
                                 let tmp = Math.floor((expiryTime - currentTime)/(60*60*24));
                                 timeLeft = tmp +" days left!";
                                }     
                                return (

                            
                                    <div key={index} className="column is-4 ">
                                    <div className="card is-rounded">
                                        
                                    <div className="card-image">
                                         
                                    <figure className="image is-4by3">
                                    <img src={urlIPFS} alt="Placeholder image"/>
                                    </figure>
                                    </div>
    
                                    <div className="card-content">
                    
                                    <div className="media">
    
                                    <div class="media-left">
                                    <figure class="image is-48x48">
                                    <img className ="is-rounded" src="passport.jpg" alt="Placeholder image"/>
                                    </figure>
                                    </div>    
    
                                    <div className="media-content">
    
                                    <h2 class="title is-4">{nft.name}</h2>
    
                                    <h2 class="subtitle is-6">{nft.creatorname}</h2>
                                    <div className = "has-text-centered">
                                    {timeLeft} 
                                    
                                    </div>
                                    </div>
    
                                      <br></br><br></br>

                                    

                                    <div class="media-right">
                                    <h2 class="title is-6">Price</h2>
    
                                    ₹{nft.listprice}
                                    </div>
                                    
                                    </div>
                                    
                                    <div className="column has-text-centered">        
                                    <a className="button is-black" onClick={ () => {buyNFT(nft)}} >Buy NFT</a>
                                    </div>            
    
                                    
                                    </div>
    
                                    </div>
                                   
                                    
                                                      
                                     </div>            

                                       
                                    )    
                            
                            })
                        }
                            </div>:

                            <div>
                                No NFTs found   
                            </div>
                        }    
                            </form>


                        
                            </nav>
                             
                            </div>
                            
                        </div>
                            
                        <br></br><br></br><br></br><br></br><br></br><br></br>
                            
                
            </div>
)


}

const Marketplace = React.forwardRef(Marketplace_);

export default Marketplace;

//<img src='loading-small.gif'/>