// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 46Sa4WMCscwEt6Udy4KXw2
// Component: 3K5VQPVjfZZA
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../../reactComponents/TextInput"; // plasmic-import: pD-B5n7bBeW/component
import Select from "../../../reactComponents/Select"; // plasmic-import: lisclnfVCzN/component
import Select__Option from "../../../reactComponents/Select__Option"; // plasmic-import: OfP8Q6aP8wv/component
import { useScreenVariants as useScreenVariantsl9NDyDlcQ3H } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: l9n-DyDlcQ3h/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_indiart_demo.module.css"; // plasmic-import: 46Sa4WMCscwEt6Udy4KXw2/projectcss
import sty from "./PlasmicCreatorProfile.module.css"; // plasmic-import: 3K5VQPVjfZZA/css
import UserSvgrepoComsvgIcon from "./icons/PlasmicIcon__UserSvgrepoComsvg"; // plasmic-import: 3tV9mqAzov1H/icon
import WalletSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__WalletSvgrepoCom1Svg"; // plasmic-import: 1xp6j2dRFJC7/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: UIKoFJyEh9dY/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: wxMYI1AVDvF5/icon
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: 9U2UTJvNDR-J/icon
import indiartBlackpngDprif0EjgCle from "./images/indiartBlackpng.png"; // plasmic-import: Dprif0EjgCLE/picture
import image5DSsF0NspDvFq from "./images/image5.jpeg"; // plasmic-import: DSsF0NspDvFQ/picture
import samaHosseiniDXypDjDzF58UnsplashjpgXcgNamGbgBqe from "./images/samaHosseiniDXypDjDzF58Unsplashjpg.jpeg"; // plasmic-import: XcgNAMGbgBqe/picture
import yellowLightFaceSilhouettejpgBhMrnDDeKfYs from "./images/yellowLightFaceSilhouettejpg.jpeg"; // plasmic-import: BhMrnDDeKfYs/picture
import goldenAutumnLeavesjpgTdwWjrxEv0JX from "./images/goldenAutumnLeavesjpg.jpeg"; // plasmic-import: TDWWjrxEV0jX/picture
import hikerLooksOutOverBaySurroundedByMountainsjpg0TYsYjEfsEm from "./images/hikerLooksOutOverBaySurroundedByMountainsjpg.jpeg"; // plasmic-import: 0t-YsYJEfsEm/picture
import peopleAtAnArtGalleryFacingTheWorkjpg2FNMpZ1RE2H from "./images/peopleAtAnArtGalleryFacingTheWorkjpg.jpeg"; // plasmic-import: 2_fNMpZ1rE2h/picture
import rustyGreenTinGraphittiWalljpgWhZqgh0UMy0Z from "./images/rustyGreenTinGraphittiWalljpg.jpeg"; // plasmic-import: whZQGH0UMy0z/picture
import aWomanStandsInAnArtGalleryInFrontOfPaintingsjpgTm9IzKHyofNd from "./images/aWomanStandsInAnArtGalleryInFrontOfPaintingsjpg.jpeg"; // plasmic-import: Tm9izKHyofND/picture
import brickWallSprayPaintArtjpgDrEwNevIyJvN from "./images/brickWallSprayPaintArtjpg.jpeg"; // plasmic-import: drEwNevIyJvN/picture
import colorfulGeometricWallArtOnAShabbyStreetjpgQTo3Q11J4U2 from "./images/colorfulGeometricWallArtOnAShabbyStreetjpg.jpeg"; // plasmic-import: qTO3q1_1j4u2/picture
import artSuppliesInRedjpgKFVe4MeXsv from "./images/artSuppliesInRedjpg.jpeg"; // plasmic-import: k-f_Ve4MEXsv/picture
import rainbowOfPaintColorsjpgYEEarUMwaQk5 from "./images/rainbowOfPaintColorsjpg.jpeg"; // plasmic-import: yEEarUMwaQK5/picture

export const PlasmicCreatorProfile__VariantProps = new Array();

export const PlasmicCreatorProfile__ArgProps = new Array();

function PlasmicCreatorProfile__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsl9NDyDlcQ3H()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__tYak)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__naHj)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kXgCm)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ia52E)}
                  displayHeight={"50px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"160px"}
                  src={{
                    src: indiartBlackpngDprif0EjgCle,
                    fullWidth: 1500,
                    fullHeight: 1500,
                    aspectRatio: undefined
                  }}
                />

                <TextInput
                  data-plasmic-name={"textInput"}
                  data-plasmic-override={overrides.textInput}
                  className={classNames("__wab_instance", sty.textInput)}
                  showStartIcon={true}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__chjVi)}
                >
                  <Select
                    className={classNames("__wab_instance", sty.select__xxTJs)}
                    placeholder={"Explore"}
                  />

                  <Select
                    className={classNames("__wab_instance", sty.select__sPLjl)}
                    placeholder={"Stats"}
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__bi2Wx
                      )}
                      value={"value1"}
                    >
                      {"Rankings"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__bIk27
                      )}
                      value={"value2"}
                    >
                      {"Activity"}
                    </Select__Option>
                  </Select>

                  <Select
                    className={classNames("__wab_instance", sty.select___7INm3)}
                    placeholder={"Resources"}
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option___5BIgo
                      )}
                      value={"value1"}
                    >
                      {"Help Center"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__toafl
                      )}
                      value={"value2"}
                    >
                      {"Platform Status"}
                    </Select__Option>

                    <Select__Option
                      className={classNames("__wab_instance", sty.option__gOQ)}
                      value={"value2 2"}
                    >
                      {"Partners"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option___5BX8N
                      )}
                      value={"value2 3"}
                    >
                      {"Gas-Free MarketPlace"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__eDrfs
                      )}
                      value={"value2 4"}
                    >
                      {"Blog"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__ludxv
                      )}
                      value={"value2 5"}
                    >
                      {"Docs"}
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__zMcle
                      )}
                      value={"value2 6"}
                    >
                      {"NewsLetter"}
                    </Select__Option>
                  </Select>
                </p.Stack>

                <a
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link
                  )}
                  href={"https://www.plasmic.app/"}
                >
                  {"Create"}
                </a>
              </p.Stack>

              <UserSvgrepoComsvgIcon
                className={classNames(projectcss.all, sty.svg__uvXcy)}
                role={"img"}
              />

              <WalletSvgrepoCom1SvgIcon
                className={classNames(projectcss.all, sty.svg__e9707)}
                role={"img"}
              />
            </p.Stack>
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__fzeB3)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__iwopj)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__slOlP)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xet4)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: image5DSsF0NspDvFq,
                    fullWidth: 640,
                    fullHeight: 427,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>

              <div className={classNames(projectcss.all, sty.column__taTnz)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oyElh
                  )}
                >
                  {"Genre"}
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xOaiq)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Adam"}
                  </h1>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__rcl9C)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tztDk
                      )}
                    >
                      {"No of Followers : 25"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7BNb
                      )}
                    >
                      {"No of Creations : 10"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8NZxu
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                    }
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__pIyAx)}
                  >
                    <Icon7Icon
                      className={classNames(projectcss.all, sty.svg__scoC)}
                      role={"img"}
                    />

                    <Icon6Icon
                      className={classNames(projectcss.all, sty.svg__jfqWo)}
                      role={"img"}
                    />

                    <Icon9Icon
                      className={classNames(projectcss.all, sty.svg__jTwHt)}
                      role={"img"}
                    />
                  </p.Stack>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ef1Hb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___716Pl
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uo2M9
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__afGbd)}
                          displayHeight={"96px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"96px"}
                          src={{
                            src: samaHosseiniDXypDjDzF58UnsplashjpgXcgNamGbgBqe,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__zjzGq
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__fxiNf)}
                          displayHeight={"96px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"96px"}
                          src={{
                            src: yellowLightFaceSilhouettejpgBhMrnDDeKfYs,
                            fullWidth: 2730,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hCRip
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__pHmJd)}
                          displayHeight={"96px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"96px"}
                          src={{
                            src: goldenAutumnLeavesjpgTdwWjrxEv0JX,
                            fullWidth: 4096,
                            fullHeight: 2730,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__iopQy
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xNyeF)}
                          displayHeight={"96px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"96px"}
                          src={{
                            src: hikerLooksOutOverBaySurroundedByMountainsjpg0TYsYjEfsEm,
                            fullWidth: 1080,
                            fullHeight: 1350,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </div>
            </p.Stack>
          </p.Stack>

          <div className={classNames(projectcss.all, sty.freeBox__spGpY)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__bavW4)}
            >
              <div className={classNames(projectcss.all, sty.column__rnaYo)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vRt0L)}
                  displayHeight={"600px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: peopleAtAnArtGalleryFacingTheWorkjpg2FNMpZ1RE2H,
                    fullWidth: 4096,
                    fullHeight: 2537,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__opnRp)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__f4R0L)}
                  displayHeight={"600px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: rustyGreenTinGraphittiWalljpgWhZqgh0UMy0Z,
                    fullWidth: 4096,
                    fullHeight: 2730,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__gim3V)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__sv4GU)}
                  displayHeight={"600px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: aWomanStandsInAnArtGalleryInFrontOfPaintingsjpgTm9IzKHyofNd,
                    fullWidth: 4096,
                    fullHeight: 4030,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </p.Stack>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__rkOeo)}
              displayHeight={"188px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"670px"}
              loading={"lazy"}
              src={{
                src: brickWallSprayPaintArtjpgDrEwNevIyJvN,
                fullWidth: 4096,
                fullHeight: 2732,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__fsVeo)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__bwOon)}
              >
                <div className={classNames(projectcss.all, sty.column___3Te60)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kCq1)}
                    displayHeight={"500px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: colorfulGeometricWallArtOnAShabbyStreetjpgQTo3Q11J4U2,
                      fullWidth: 4096,
                      fullHeight: 2731,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__uSppy)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gmIGg)}
                    displayHeight={"500px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: artSuppliesInRedjpgKFVe4MeXsv,
                      fullWidth: 4096,
                      fullHeight: 2730,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.freeBox__tqU4)}>
                <div className={classNames(projectcss.all, sty.freeBox__lIfGz)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ji6I6)}
                    displayHeight={"600px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"610px"}
                    loading={"lazy"}
                    src={{
                      src: rainbowOfPaintColorsjpgYEEarUMwaQk5,
                      fullWidth: 4096,
                      fullHeight: 3280,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "textInput", "textbox", "link", "h1"],
  textInput: ["textInput", "textbox"],
  link: ["link"],
  h1: ["h1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCreatorProfile__ArgProps,
      internalVariantPropNames: PlasmicCreatorProfile__VariantProps
    });

    return PlasmicCreatorProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCreatorProfile";
  } else {
    func.displayName = `PlasmicCreatorProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicCreatorProfile = Object.assign(
  // Top-level PlasmicCreatorProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    link: makeNodeComponent("link"),
    h1: makeNodeComponent("h1"),
    // Metadata about props expected for PlasmicCreatorProfile
    internalVariantProps: PlasmicCreatorProfile__VariantProps,
    internalArgProps: PlasmicCreatorProfile__ArgProps
  }
);

export default PlasmicCreatorProfile;
/* prettier-ignore-end */
