// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 46Sa4WMCscwEt6Udy4KXw2
// Component: GFn7UWEtp4r1
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../../reactComponents/Navbar"; // plasmic-import: 5MSC0M28Vln/component
import Button from "../../../reactComponents/Button"; // plasmic-import: H6IfdFc-NOE-/component
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent
import { useScreenVariants as useScreenVariantsl9NDyDlcQ3H } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: l9n-DyDlcQ3h/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_indiart_demo.module.css"; // plasmic-import: 46Sa4WMCscwEt6Udy4KXw2/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: GFn7UWEtp4r1/css
import ImageSvgrepoComsvgIcon from "./icons/PlasmicIcon__ImageSvgrepoComsvg"; // plasmic-import: TIflUYTr1rtf/icon
import WalletSvgrepoComsvgIcon from "./icons/PlasmicIcon__WalletSvgrepoComsvg"; // plasmic-import: ffAnZsN_wlRn/icon
import CollectionSvgrepoComsvgIcon from "./icons/PlasmicIcon__CollectionSvgrepoComsvg"; // plasmic-import: 4ztbfV1F6N7H/icon
import ListSvgrepoComsvgIcon from "./icons/PlasmicIcon__ListSvgrepoComsvg"; // plasmic-import: 55qxcVSgRAgt/icon
import yellowLightFaceSilhouettejpgBhMrnDDeKfYs from "./images/yellowLightFaceSilhouettejpg.jpeg"; // plasmic-import: BhMrnDDeKfYs/picture
import handfulOfBitcoinCryptocurrencyjpgOvcTcQzziHbC from "./images/handfulOfBitcoinCryptocurrencyjpg.jpeg"; // plasmic-import: OvcTCQzziHbC/picture
import manLiftsTireExercisejpgG9IB6KPmD4OP from "./images/manLiftsTireExercisejpg.jpeg"; // plasmic-import: G9iB6KPmD4oP/picture
import samaHosseiniDXypDjDzF58UnsplashjpgXcgNamGbgBqe from "./images/samaHosseiniDXypDjDzF58Unsplashjpg.jpeg"; // plasmic-import: XcgNAMGbgBqe/picture
import susanWilkinsonQ8HQYzt7RFoUnsplashjpgIpYmMu7DbWgt from "./images/susanWilkinsonQ8HQYzt7RFoUnsplashjpg.jpeg"; // plasmic-import: ipYMMu7DBWgt/picture
import asphaltHighwayjpgUcJrYwxi81Xs from "./images/asphaltHighwayjpg.jpeg"; // plasmic-import: UcJRYwxi81Xs/picture
import goldenAutumnLeavesjpgTdwWjrxEv0JX from "./images/goldenAutumnLeavesjpg.jpeg"; // plasmic-import: TDWWjrxEV0jX/picture
import longForestPathjpgWXn0M9VpS5Fl from "./images/longForestPathjpg.jpeg"; // plasmic-import: WXn0M9VpS5FL/picture
import hikerLooksOutOverBaySurroundedByMountainsjpg0TYsYjEfsEm from "./images/hikerLooksOutOverBaySurroundedByMountainsjpg.jpeg"; // plasmic-import: 0t-YsYJEfsEm/picture
import lemursSittingOnLogjpgGvj5WSVjGHuv from "./images/lemursSittingOnLogjpg.jpeg"; // plasmic-import: gvj5wSVjGHuv/picture
import aSingleBrownSpeckledEggInALittleNestjpgU4W67QjRTeWn from "./images/aSingleBrownSpeckledEggInALittleNestjpg.jpeg"; // plasmic-import: u4w67qjRTeWN/picture
import image21SOwQf2Gnmsff from "./images/image21.jpeg"; // plasmic-import: sOwQF2Gnmsff/picture
import image5DSsF0NspDvFq from "./images/image5.jpeg"; // plasmic-import: DSsF0NspDvFQ/picture
import image6YuYHiMJto from "./images/image6.jpeg"; // plasmic-import: yuYHi_m_jto-/picture
import image8OZDQyEib6Nf from "./images/image8.jpeg"; // plasmic-import: oZ-dQYEib6nf/picture
import image9F41AHjhK20U4 from "./images/image9.png"; // plasmic-import: f41AHjhK20U4/picture
import image16R18Nqt0R5Lqi from "./images/image16.jpeg"; // plasmic-import: R18Nqt0r5Lqi/picture
import image44DbeJuXsgj6G from "./images/image4.png"; // plasmic-import: 4DBEJuXsgj6g/picture
import image29LjQzx7Jqw28 from "./images/image29.jpeg"; // plasmic-import: LJQzx7jqw28-/picture
import image447H10Pdq2D40M from "./images/image44.jpeg"; // plasmic-import: 7H10Pdq2D40m/picture
import designersDeskFlatlayjpgDp7TvC1Ux16R from "./images/designersDeskFlatlayjpg.jpeg"; // plasmic-import: DP7TvC1Ux16r/picture
import assortmentOfToysOnPinkjpg4PDwnhy7Ciov from "./images/assortmentOfToysOnPinkjpg.jpeg"; // plasmic-import: 4pDwnhy7ciov/picture
import artsCraftsInBluejpgJJr4Ae3TtDgu from "./images/artsCraftsInBluejpg.jpeg"; // plasmic-import: jJr4Ae3TtDgu/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsl9NDyDlcQ3H()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___1THvs)}>
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__b04Z)} />

          <div className={classNames(projectcss.all, sty.freeBox__yo110)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__gIypK
              )}
            >
              {"Top Collections"}
            </h1>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__dEMgv)}
            >
              <div className={classNames(projectcss.all, sty.column__nktRa)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mzfQg)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: yellowLightFaceSilhouettejpgBhMrnDDeKfYs,
                    fullWidth: 2730,
                    fullHeight: 4096,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__brqBu)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qyQce)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rXtPu
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yvyE8
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b73BF
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hifUe
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__svDRi)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__e6FBd)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: handfulOfBitcoinCryptocurrencyjpgOvcTcQzziHbC,
                    fullWidth: 4096,
                    fullHeight: 2730,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lVQy)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__xe888)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__we6Uw
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f6QyF
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kYvRi
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kyDe1
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__akdKd)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5DlaK)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: manLiftsTireExercisejpgG9IB6KPmD4OP,
                    fullWidth: 4096,
                    fullHeight: 2732,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wYdw5)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___1Tkv0)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rp39Q
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g4Wng
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lTj4V
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qQ62
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__xCnmP)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__z576Z)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: samaHosseiniDXypDjDzF58UnsplashjpgXcgNamGbgBqe,
                    fullWidth: 3276,
                    fullHeight: 4096,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dtOjh)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__fidH)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gPdWk
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hu6X5
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qC9Oz
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cFc8
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__oIugw)}
            >
              <div className={classNames(projectcss.all, sty.column__selMl)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__lu0E6)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: susanWilkinsonQ8HQYzt7RFoUnsplashjpgIpYmMu7DbWgt,
                    fullWidth: 2730,
                    fullHeight: 4096,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__oIrNy)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__viGv2)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z6Yv
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jAaNk
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___10M5
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yKhm4
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__wu11I)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__lEkzv)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: asphaltHighwayjpgUcJrYwxi81Xs,
                    fullWidth: 4096,
                    fullHeight: 2731,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hIdU)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ux2Nx)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wCUzx
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o0Qbz
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4GL0K
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dT2Kd
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__w1Nh6)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bi6Ws)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: goldenAutumnLeavesjpgTdwWjrxEv0JX,
                    fullWidth: 4096,
                    fullHeight: 2730,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dl9EY)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rcdb)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__j44M
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5GYj
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__scEwb
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z2QxY
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__e0Uij)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ibXdF)}
                  displayHeight={"300px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: longForestPathjpgWXn0M9VpS5Fl,
                    fullWidth: 2731,
                    fullHeight: 4096,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__twg)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zbnSi)}
                    displayHeight={"96px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rczEz
                    )}
                  >
                    {"Project 1"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rnbqe
                    )}
                  >
                    {"Tracy"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y15G0
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wBl4X
                    )}
                  >
                    {"Price :  5 ETH"}
                  </div>
                </p.Stack>
              </div>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__ljV7V)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1___1Q3Pg
              )}
            >
              {"Browse by Category"}
            </h1>

            <div className={classNames(projectcss.all, sty.columns__fR3D)}>
              <div className={classNames(projectcss.all, sty.column__sguPc)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__jgjjf)}
                  displayHeight={"338px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: hikerLooksOutOverBaySurroundedByMountainsjpg0TYsYjEfsEm,
                    fullWidth: 1080,
                    fullHeight: 1350,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__xgSyy
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4___7MmMb
                    )}
                  >
                    {"Nature"}
                  </h4>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__ehvvC)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3K9G)}
                  displayHeight={"338px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: lemursSittingOnLogjpgGvj5WSVjGHuv,
                    fullWidth: 2730,
                    fullHeight: 4096,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__uPsk9
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__aaeDv
                    )}
                  >
                    {"WildLife"}
                  </h4>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__ykr9)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hvzJl)}
                  displayHeight={"338px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: aSingleBrownSpeckledEggInALittleNestjpgU4W67QjRTeWn,
                    fullWidth: 4096,
                    fullHeight: 2730,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___5WwtF
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4___5HOin
                    )}
                  >
                    {"Still Life"}
                  </h4>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__apQeM)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__w2Xve)}
                  displayHeight={"338px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: image21SOwQf2Gnmsff,
                    fullWidth: 1800,
                    fullHeight: 1201,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__sa9LW
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__h9Ato
                    )}
                  >
                    {"Work"}
                  </h4>
                </p.Stack>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___07Osn)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__bUuI
              )}
            >
              {"Creators on Indiart"}
            </h1>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___6JqQ9)}
            >
              <div className={classNames(projectcss.all, sty.column__hQlU)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3Mum)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image5DSsF0NspDvFq,
                    fullWidth: 640,
                    fullHeight: 427,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___3XoYa
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__xgSei
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__fdR1E)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tcPw5
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eEk3V
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__snXzb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uokhi
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ywniY
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__r6EQi)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__k83Vj)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gMiV0)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image6YuYHiMJto,
                    fullWidth: 640,
                    fullHeight: 427,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__tdHo
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__puMa6
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___47WQn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1TU4O
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dm8
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__goAwd)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__shoqb
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vjZeM
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__q3FU)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__rYOf2)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hJmLd)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image8OZDQyEib6Nf,
                    fullWidth: 640,
                    fullHeight: 426,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___4NPri
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__amAu6
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__tHpl9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sbAj
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lSsjq
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__tYbGn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qdPcq
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__swUdl
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__i7EK)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__kA9Su)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rxUyH)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image9F41AHjhK20U4,
                    fullWidth: 774,
                    fullHeight: 1161,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__nsKt
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__mZojF
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__gnqVh)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0Lj3Y
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mRrSe
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___0Mp8J)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dim4
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s5AJv
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__iccHk)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ulQOv)}
            >
              <div className={classNames(projectcss.all, sty.column__jvYaK)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__m8C3B)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image16R18Nqt0R5Lqi,
                    fullWidth: 1920,
                    fullHeight: 1280,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__trFsG
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__antOm
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__f4Dfy)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__o8Ysd
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aL6Te
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__nEg4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Kzpx
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__knlO
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__wC8V)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column___0XGyc)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__je64K)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image44DbeJuXsgj6G,
                    fullWidth: 1287,
                    fullHeight: 1931,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__se6Fo
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__pbJGg
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___7Up6H)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fUcgp
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0SCg
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__qKYyj)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m4JgL
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4YfNr
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__ja0Tb)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__nJdl)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yYoT)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image29LjQzx7Jqw28,
                    fullWidth: 225,
                    fullHeight: 225,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__acTu
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4___2Rfzb
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___7OdT2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___34BkP
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nezuz
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ooLog)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ffFhV
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nVr16
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__lSo5C)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column___2Jif5)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__iok2D)}
                  displayHeight={"200px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"auto"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: image447H10Pdq2D40M,
                    fullWidth: 1920,
                    fullHeight: 1279,
                    aspectRatio: undefined
                  }}
                />

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__q1NKm
                  )}
                >
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__pV4Qj
                    )}
                  >
                    {"Doi lorem Name"}
                  </h4>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__umAt1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vSf3
                      )}
                    >
                      {"@name"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mSwOg
                    )}
                  >
                    {"Genre of Art"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__boKu1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h83Sk
                      )}
                    >
                      {"55 Creations"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rNxXx
                      )}
                    >
                      {"600 Followers"}
                    </div>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button___1ArHm)}
                    color={"softSand"}
                  >
                    {"Follow"}
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__mWjj)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__b2N1)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__kpfyk
                  )}
                >
                  {"Create and Sell your NFTs"}
                </h1>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__gMKkX)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__a9Lug)}
                  >
                    <ImageSvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__lxNe)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rkwt0
                      )}
                    >
                      {"Set up your wallet"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__o77Pf
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printin and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                      }
                    </div>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__u8YN)}>
                    <WalletSvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__uvz79)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__spAvv
                      )}
                    >
                      {"Set up your wallet"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gBBl
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                      }
                    </div>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__z5BV)}>
                    <CollectionSvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__lFyuH)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rmfsc
                      )}
                    >
                      {"Set up your wallet"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pWE
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printingand typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___0BH2D)}
                  >
                    <ListSvgrepoComsvgIcon
                      className={classNames(projectcss.all, sty.svg__gxp1D)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sAOlU
                      )}
                    >
                      {"Set up your wallet"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uLn9
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                      }
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__dLdQz)}>
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1__l1MI
              )}
            >
              {"Resources for getting Started"}
            </h1>

            <div className={classNames(projectcss.all, sty.columns__lsc7N)}>
              <div className={classNames(projectcss.all, sty.column__vuDC)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cPtSd)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: designersDeskFlatlayjpgDp7TvC1Ux16R,
                    fullWidth: 4096,
                    fullHeight: 2730,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__nmJes)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tGlwq)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: assortmentOfToysOnPinkjpg4PDwnhy7Ciov,
                    fullWidth: 4096,
                    fullHeight: 2172,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__ardxo)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dAlSl)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: artsCraftsInBluejpgJJr4Ae3TtDgu,
                    fullWidth: 4096,
                    fullHeight: 2730,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__dhHxq)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__wHxDr
                )}
              >
                {"Meet IndiArt"}
              </h1>

              <YouTube
                data-plasmic-name={"youTube"}
                data-plasmic-override={overrides.youTube}
                className={classNames("__wab_instance", sty.youTube)}
                videoId={"R6MeLqRQzYw"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navbar", "youTube"],
  navbar: ["navbar"],
  youTube: ["youTube"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    youTube: makeNodeComponent("youTube"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
