// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 46Sa4WMCscwEt6Udy4KXw2
// Component: ITRhXvzT_jL3
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../../reactComponents/Button"; // plasmic-import: H6IfdFc-NOE-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_indiart_demo.module.css"; // plasmic-import: 46Sa4WMCscwEt6Udy4KXw2/projectcss
import sty from "./PlasmicSignup.module.css"; // plasmic-import: ITRhXvzT_jL3/css

export const PlasmicSignup__VariantProps = new Array();

export const PlasmicSignup__ArgProps = new Array();

function PlasmicSignup__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__lDhRp)}>
            <div className={classNames(projectcss.all, sty.freeBox__ytPl)}>
              <Button
                data-plasmic-name={"signupwithEmail"}
                data-plasmic-override={overrides.signupwithEmail}
                className={classNames("__wab_instance", sty.signupwithEmail)}
              >
                {"Signup with Email"}
              </Button>

              <Button
                data-plasmic-name={"signupwithFb"}
                data-plasmic-override={overrides.signupwithFb}
                className={classNames("__wab_instance", sty.signupwithFb)}
              >
                {"Signup with Facebook"}
              </Button>

              <Button
                data-plasmic-name={"signupwithGoogle"}
                data-plasmic-override={overrides.signupwithGoogle}
                className={classNames("__wab_instance", sty.signupwithGoogle)}
              >
                {"Signup with Google"}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "signupwithEmail", "signupwithFb", "signupwithGoogle"],
  signupwithEmail: ["signupwithEmail"],
  signupwithFb: ["signupwithFb"],
  signupwithGoogle: ["signupwithGoogle"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSignup__ArgProps,
      internalVariantPropNames: PlasmicSignup__VariantProps
    });

    return PlasmicSignup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignup";
  } else {
    func.displayName = `PlasmicSignup.${nodeName}`;
  }
  return func;
}

export const PlasmicSignup = Object.assign(
  // Top-level PlasmicSignup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    signupwithEmail: makeNodeComponent("signupwithEmail"),
    signupwithFb: makeNodeComponent("signupwithFb"),
    signupwithGoogle: makeNodeComponent("signupwithGoogle"),
    // Metadata about props expected for PlasmicSignup
    internalVariantProps: PlasmicSignup__VariantProps,
    internalArgProps: PlasmicSignup__ArgProps
  }
);

export default PlasmicSignup;
/* prettier-ignore-end */
