// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 46Sa4WMCscwEt6Udy4KXw2
// Component: wzQg7co5grOH
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Navbar from "../../../reactComponents/Navbar"; // plasmic-import: 5MSC0M28Vln/component
import Select from "../../../reactComponents/Select"; // plasmic-import: lisclnfVCzN/component
import Select__Option from "../../../reactComponents/Select__Option"; // plasmic-import: OfP8Q6aP8wv/component
import Checkbox from "../../../reactComponents/Checkbox"; // plasmic-import: AKhkWq92AhN/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_indiart_demo.module.css"; // plasmic-import: 46Sa4WMCscwEt6Udy4KXw2/projectcss
import sty from "./PlasmicMarketPlace.module.css"; // plasmic-import: wzQg7co5grOH/css
import EthereumSvgrepoComsvgIcon from "./icons/PlasmicIcon__EthereumSvgrepoComsvg"; // plasmic-import: WQIwI5k2eoMf/icon
import HeartSvgrepoComsvgIcon from "./icons/PlasmicIcon__HeartSvgrepoComsvg"; // plasmic-import: YYHHcclC5f3p/icon
import hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S from "./images/hikerLooksUpAtVerticalMountainPeaksjpg.jpeg"; // plasmic-import: mG3dMTvipD5S/picture

export const PlasmicMarketPlace__VariantProps = new Array();

export const PlasmicMarketPlace__ArgProps = new Array(
  "nft1",
  "nft2",
  "nft3",
  "name1",
  "price1",
  "name2",
  "price2",
  "name3",
  "price3",
  "name4",
  "price4",
  "name5",
  "price5",
  "name6",
  "price6",
  "name7",
  "price7",
  "name8",
  "price8"
);

function PlasmicMarketPlace__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__e6Zxy)}>
            <div className={classNames(projectcss.all, sty.freeBox__pMcol)}>
              <Navbar
                data-plasmic-name={"navbar"}
                data-plasmic-override={overrides.navbar}
                className={classNames("__wab_instance", sty.navbar)}
              />
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__qgD)}
            >
              <div className={classNames(projectcss.all, sty.column__wToQl)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__l1Rrx)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cJdKx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fBEnT
                      )}
                    >
                      {"Filter"}
                    </div>
                  </div>

                  <Select
                    className={classNames("__wab_instance", sty.select__daTXy)}
                    placeholder={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s4MQh
                        )}
                      >
                        {"Status"}
                      </div>
                    }
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option___4Vdfh
                      )}
                      value={"value1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6MXs7
                        )}
                      >
                        {"Buy Now"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__zh7H9
                      )}
                      value={"value1 2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jne8D
                        )}
                      >
                        {"On Auction"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__bao8Q
                      )}
                      value={"value1 4"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3Oorw
                        )}
                      >
                        {"New"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option___29Nu
                      )}
                      value={"value1 5"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yn7X6
                        )}
                      >
                        {"Has Offers"}
                      </div>
                    </Select__Option>
                  </Select>

                  <Select
                    className={classNames("__wab_instance", sty.select__zYKuY)}
                    placeholder={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vuwil
                        )}
                      >
                        {"Price"}
                      </div>
                    }
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__kuocg
                      )}
                      value={"value1 2"}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox__ip3Gl
                        )}
                      >
                        {"USD"}
                      </Checkbox>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__yiHaR
                      )}
                      value={"value1 3"}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox___6FhIn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eHibd
                          )}
                        >
                          {"Ether"}
                        </div>
                      </Checkbox>
                    </Select__Option>
                  </Select>

                  <Select
                    className={classNames("__wab_instance", sty.select__kf89A)}
                    placeholder={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zwmbr
                        )}
                      >
                        {"Collections"}
                      </div>
                    }
                  />

                  <Select
                    className={classNames("__wab_instance", sty.select__vrxq5)}
                    placeholder={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___49MMx
                        )}
                      >
                        {"Chains"}
                      </div>
                    }
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__fVchY
                      )}
                      value={"value1"}
                    >
                      <EthereumSvgrepoComsvgIcon
                        className={classNames(projectcss.all, sty.svg___7PjcC)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mEcRm
                        )}
                      >
                        {"Ethereum"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__zh7H9
                      )}
                      value={"value1 2"}
                    >
                      <EthereumSvgrepoComsvgIcon
                        className={classNames(projectcss.all, sty.svg__eOoOo)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mEcRm
                        )}
                      >
                        {"Matic"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__bao8Q
                      )}
                      value={"value1 4"}
                    >
                      <EthereumSvgrepoComsvgIcon
                        className={classNames(projectcss.all, sty.svg__cVnhi)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mEcRm
                        )}
                      >
                        {"Klaytln"}
                      </div>
                    </Select__Option>
                  </Select>

                  <Select
                    className={classNames("__wab_instance", sty.select__y0Mk)}
                    placeholder={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lnV5D
                        )}
                      >
                        {"Category"}
                      </div>
                    }
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__opZ29
                      )}
                      value={"value1"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xoGrL
                        )}
                      >
                        {"Art"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__zh7H9
                      )}
                      value={"value1 2"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b6XvD
                        )}
                      >
                        {"Photography"}
                      </div>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__bao8Q
                      )}
                      value={"value1 4"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8EkFo
                        )}
                      >
                        {"Paint"}
                      </div>
                    </Select__Option>
                  </Select>

                  <Select
                    className={classNames("__wab_instance", sty.select__ms1Ls)}
                    placeholder={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r0Vbf
                        )}
                      >
                        {"On Sale in"}
                      </div>
                    }
                  >
                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option___6Uw0O
                      )}
                      value={"value1 2"}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox__e8IH
                        )}
                      >
                        {"Ethereum"}
                      </Checkbox>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__yiHaR
                      )}
                      value={"value1 3"}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox___7Nuxd
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zy4Vf
                          )}
                        >
                          {"Matic"}
                        </div>
                      </Checkbox>
                    </Select__Option>

                    <Select__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__ccrwV
                      )}
                      value={"value1 5"}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox__guuOk
                        )}
                      >
                        {"Solana"}
                      </Checkbox>
                    </Select__Option>
                  </Select>
                </p.Stack>
              </div>

              <div className={classNames(projectcss.all, sty.column__ndNn4)}>
                <div className={classNames(projectcss.all, sty.freeBox__rBhg2)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xUdh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__kc63G)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__voPp4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fkW9B
                          )}
                        >
                          {"500000 items"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dnZjn
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y9AlC
                          )}
                        >
                          <Select
                            className={classNames(
                              "__wab_instance",
                              sty.select__qoBh1
                            )}
                            placeholder={"All items"}
                          >
                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option__aiQ8
                              )}
                              value={"value1"}
                            >
                              {"Single Items"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option__liVcv
                              )}
                              value={"value2"}
                            >
                              {"Bundles"}
                            </Select__Option>
                          </Select>

                          <Select
                            className={classNames(
                              "__wab_instance",
                              sty.select__fcrCm
                            )}
                            placeholder={"Sort by"}
                          >
                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option___3Fbfr
                              )}
                              value={"value1"}
                            >
                              {"Recently Listed"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option__tUpvm
                              )}
                              value={"value1 2"}
                            >
                              {"Recently Created"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option___21CDs
                              )}
                              value={"value1 3"}
                            >
                              {"Recently Sold"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option__jnn4E
                              )}
                              value={"value1 4"}
                            >
                              {"Recently Received"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option___6Pw7O
                              )}
                              value={"value1 5"}
                            >
                              {"Ending Soon"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option__we07D
                              )}
                              value={"value1 6"}
                            >
                              {"Price : Low to High"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option___2VsE
                              )}
                              value={"value2"}
                            >
                              {"Price : High to Low"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option__pUUr
                              )}
                              value={"value2 2"}
                            >
                              {"Highest Last Sale"}
                            </Select__Option>

                            <Select__Option
                              className={classNames(
                                "__wab_instance",
                                sty.option___3EnGw
                              )}
                              value={"value2 3"}
                            >
                              {"Oldest"}
                            </Select__Option>
                          </Select>
                        </p.Stack>
                      </div>
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xfyjO)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__csZws)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__eaI9V
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: (
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__dZp0H)}
                              displayHeight={"199px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"100%"}
                              loading={"lazy"}
                              src={{
                                src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                                fullWidth: 3276,
                                fullHeight: 4096,
                                aspectRatio: undefined
                              }}
                            />
                          ),

                          value: args.nft1
                        })}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lQ8Vs
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tk6WM
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zwXoj
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2LjQl
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__hYuoz
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__r3Mnd
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name1
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__mnCqD
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price1,
                                className: classNames(sty.slotTargetPrice1)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__caLvH
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__g1XIu
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vBgPr
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wxZB
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__xDcDe
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: (
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__b4QOs)}
                              displayHeight={"199px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"100%"}
                              loading={"lazy"}
                              src={{
                                src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                                fullWidth: 3276,
                                fullHeight: 4096,
                                aspectRatio: undefined
                              }}
                            />
                          ),

                          value: args.nft2
                        })}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oRcqX
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__af2
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___3Huto
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__t0S7N
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tnIr
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__jTPnE
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name2
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fSs5Z
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price2,
                                className: classNames(sty.slotTargetPrice2)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pyFhh
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bvoEd
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rLpnc
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uVg9T
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___69Let
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: (
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__hFDma)}
                              displayHeight={"199px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"100%"}
                              loading={"lazy"}
                              src={{
                                src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                                fullWidth: 3276,
                                fullHeight: 4096,
                                aspectRatio: undefined
                              }}
                            />
                          ),

                          value: args.nft3
                        })}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__r0NT
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__eIAi
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__k4Ug2
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bvZTa
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___2XjAt
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__mdPsa
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name3
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ud9Nz
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price3,
                                className: classNames(sty.slotTargetPrice3)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___4WcWe
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__miMQk
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__p32TF
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oAzxF
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4XbJf
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"nft4"}
                          data-plasmic-override={overrides.nft4}
                          alt={""}
                          className={classNames(sty.nft4)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___6X0Ig
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__xlMk
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wdhCe
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ckgUj
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___7LPan
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__g1HOi
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name4
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ukyfj
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price4,
                                className: classNames(sty.slotTargetPrice4)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tbUzZ
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__onnOv
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jqWdg
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bzDxp
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.columns__gXwzO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3WHlX
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"nft5"}
                          data-plasmic-override={overrides.nft5}
                          alt={""}
                          className={classNames(sty.nft5)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2CwU
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__deCst
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__aSwdy
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__i31Kz
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vKt76
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___27Ssl
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name5
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__ols0J
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price5,
                                className: classNames(sty.slotTargetPrice5)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sn5T8
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vutD1
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mRxxz
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___83MW4
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4HpD6
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"nft6"}
                          data-plasmic-override={overrides.nft6}
                          alt={""}
                          className={classNames(sty.nft6)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___0ExAh
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___1LlEp
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bSnmd
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ayhq
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vrmRk
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__zgqRx
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name6
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__drM
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price6,
                                className: classNames(sty.slotTargetPrice6)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mNfto
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vl2IR
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__d75Uy
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aLxOt
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dkFg7
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"nft7"}
                          data-plasmic-override={overrides.nft7}
                          alt={""}
                          className={classNames(sty.nft7)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gcC3P
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__u7T59
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eram
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__m2Kks
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__v3OFy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__nxMd
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name7
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__d9Rh3
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price7,
                                className: classNames(sty.slotTargetPrice7)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gnZpx
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__bxL2
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fLOtZ
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nGBhp
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__aJuLd
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"nft8"}
                          data-plasmic-override={overrides.nft8}
                          alt={""}
                          className={classNames(sty.nft8)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vgYmm
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__s2C5
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mapYc
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ahurZ
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__sWqa3
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__tDeg
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "Name",
                                value: args.name8
                              })}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___9ZnUv
                              )}
                            >
                              {p.renderPlasmicSlot({
                                defaultContents: "0.08",
                                value: args.price8,
                                className: classNames(sty.slotTargetPrice8)
                              })}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__f64K0
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___5VnPs
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ngwLa
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xvxHz
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.columns__bsdq2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___7Cm2Z
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__dddVx)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fEput
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bxsrF
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oIRuh
                              )}
                            >
                              {"Nature"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xsb3X
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__d1CFd
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xznxV
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ceO4
                              )}
                            >
                              {"0.08"}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lm0WU
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___2FXd
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jbXGw
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__x43Pq
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___5FSdc
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__a3Nnx)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ytSf3
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ueazZ
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___8Du8Z
                              )}
                            >
                              {"Nature"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__eV6A
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ebGPt
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zSzZp
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ew04A
                              )}
                            >
                              {"0.08"}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__x8Ij9
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ylkDb
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uZgK
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___8Ir45
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__qXRv6
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xCvdk)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bn2Fg
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bhUtI
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uoKt
                              )}
                            >
                              {"Nature"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fMqT
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__meIj6
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__pgHs9
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___0W9Ad
                              )}
                            >
                              {"0.08"}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bXw0S
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__w134B
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__c9Aiw
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__riFkE
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__ypIy)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ryjVk)}
                          displayHeight={"199px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: hikerLooksUpAtVerticalMountainPeaksjpgMG3DMTvipD5S,
                            fullWidth: 3276,
                            fullHeight: 4096,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gTrnP
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__fxuAi
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fxYdx
                              )}
                            >
                              {"Nature"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__q0EhP
                              )}
                            >
                              {"Price"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ufL8J
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nMcHa
                              )}
                            >
                              {"Name"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__g4Qqi
                              )}
                            >
                              {"0.08"}
                            </div>
                          </div>
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__c8Uje
                          )}
                        >
                          <EthereumSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zd0Xl
                            )}
                            role={"img"}
                          />

                          <HeartSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4PChm
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zsErZ
                            )}
                          >
                            {"2"}
                          </div>
                        </p.Stack>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navbar", "nft4", "nft5", "nft6", "nft7", "nft8"],
  navbar: ["navbar"],
  nft4: ["nft4"],
  nft5: ["nft5"],
  nft6: ["nft6"],
  nft7: ["nft7"],
  nft8: ["nft8"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMarketPlace__ArgProps,
      internalVariantPropNames: PlasmicMarketPlace__VariantProps
    });

    return PlasmicMarketPlace__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMarketPlace";
  } else {
    func.displayName = `PlasmicMarketPlace.${nodeName}`;
  }
  return func;
}

export const PlasmicMarketPlace = Object.assign(
  // Top-level PlasmicMarketPlace renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    nft4: makeNodeComponent("nft4"),
    nft5: makeNodeComponent("nft5"),
    nft6: makeNodeComponent("nft6"),
    nft7: makeNodeComponent("nft7"),
    nft8: makeNodeComponent("nft8"),
    // Metadata about props expected for PlasmicMarketPlace
    internalVariantProps: PlasmicMarketPlace__VariantProps,
    internalArgProps: PlasmicMarketPlace__ArgProps
  }
);

export default PlasmicMarketPlace;
/* prettier-ignore-end */
