// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 46Sa4WMCscwEt6Udy4KXw2
// Component: wuYTc58rKmTo
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../../reactComponents/TextInput"; // plasmic-import: pD-B5n7bBeW/component
import Button from "../../../reactComponents/Button"; // plasmic-import: H6IfdFc-NOE-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_indiart_demo.module.css"; // plasmic-import: 46Sa4WMCscwEt6Udy4KXw2/projectcss
import sty from "./PlasmicSignupWithEmail.module.css"; // plasmic-import: wuYTc58rKmTo/css

export const PlasmicSignupWithEmail__VariantProps = new Array();

export const PlasmicSignupWithEmail__ArgProps = new Array();

function PlasmicSignupWithEmail__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__lg1Mb)}>
            <div className={classNames(projectcss.all, sty.freeBox__fcm0K)}>
              <TextInput
                data-plasmic-name={"emailId"}
                data-plasmic-override={overrides.emailId}
                className={classNames("__wab_instance", sty.emailId)}
                placeholder={"Email ID"}
              />

              <TextInput
                data-plasmic-name={"username"}
                data-plasmic-override={overrides.username}
                className={classNames("__wab_instance", sty.username)}
                placeholder={"Username"}
              />

              <TextInput
                data-plasmic-name={"password"}
                data-plasmic-override={overrides.password}
                className={classNames("__wab_instance", sty.password)}
                placeholder={"Password"}
              />

              <TextInput
                data-plasmic-name={"confirmpassword"}
                data-plasmic-override={overrides.confirmpassword}
                className={classNames("__wab_instance", sty.confirmpassword)}
                placeholder={"Confirm Password"}
              />

              <Button
                data-plasmic-name={"submit"}
                data-plasmic-override={overrides.submit}
                className={classNames("__wab_instance", sty.submit)}
              >
                {"Submit"}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "emailId",
    "username",
    "password",
    "confirmpassword",
    "submit"
  ],

  emailId: ["emailId"],
  username: ["username"],
  password: ["password"],
  confirmpassword: ["confirmpassword"],
  submit: ["submit"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSignupWithEmail__ArgProps,
      internalVariantPropNames: PlasmicSignupWithEmail__VariantProps
    });

    return PlasmicSignupWithEmail__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignupWithEmail";
  } else {
    func.displayName = `PlasmicSignupWithEmail.${nodeName}`;
  }
  return func;
}

export const PlasmicSignupWithEmail = Object.assign(
  // Top-level PlasmicSignupWithEmail renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    emailId: makeNodeComponent("emailId"),
    username: makeNodeComponent("username"),
    password: makeNodeComponent("password"),
    confirmpassword: makeNodeComponent("confirmpassword"),
    submit: makeNodeComponent("submit"),
    // Metadata about props expected for PlasmicSignupWithEmail
    internalVariantProps: PlasmicSignupWithEmail__VariantProps,
    internalArgProps: PlasmicSignupWithEmail__ArgProps
  }
);

export default PlasmicSignupWithEmail;
/* prettier-ignore-end */
